-- Queries for User table

DROP TABLE USER;

CREATE TABLE USER (USERNAME VARCHAR(10) PRIMARY KEY, PASSWORD VARCHAR(15), ROLE VARCHAR(15));

insert into USER (USERNAME, PASSWORD, ROLE) VALUES ('User1', '123456', 'ROLE_USER');
insert into USER (USERNAME, PASSWORD, ROLE) VALUES ('User2', '654321', 'ROLE_ADMIN');